# Configuración de Filebeat para enviar datos a Elasticsearch
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ./C:/Users/pfabi/OneDrive/Escritorio/computo_nube/ekl/nyc_collision_data.csv

# Configuración de la salida de datos a Elasticsearch
output.elasticsearch:
  hosts: ["localhost:9200"]
  index: nyc_visionzero
  pipeline: nyc_collision

# Configuración de módulos de Filebeat (no se usan en este ejemplo)
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Configuración de la plantilla de índice
setup.template.settings:
  index.number_of_shards: 1

setup.template.name: "nyc_collision"
setup.template.pattern: "nyc_collision-*"

# Configuración para conectarse a Kibana
setup.kibana:
  host: "localhost:5601"

# Procesadores adicionales (metadatos de host y nube)
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
